# ğ’ğ­ğšğ¬ğ¡ è‡ªç”¨é…ç½®
# ğ”ğ‘ğ‹ï¼š https://raw.githubusercontent.com/gzxiexl/Myself/main/Stash/Config.yaml?token=GHSAT0AAAAAACE7IQ5AYORNZX5OGXVQITQSZKJ5YLQ
# ğ”ğ©ğğšğ­ğï¼š 2023.11.07

mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: Rule
log-level: info
ipv6: true
external-controller: :9090

# > æœºåœºæµé‡ä¿¡æ¯
subscribe-url: https://dy.ssrla.de/link/8oeOWH40JDaAtcHY?clash=1

proxy-providers:
  ğŸ›« æˆ‘çš„æœºåœº:
    type: http
    url: "https://dy.ssrla.de/link/8oeOWH40JDaAtcHY?clash=1"
    interval: 86400
    filter: é¦™æ¸¯|å°æ¹¾|æ—¥æœ¬|éŸ©å›½|æ–°åŠ å¡|ç¾å›½
    path: ./airport.yaml
    health-check:
      enable: true
      interval: 600
      url: http://cp.cloudflare.com/generate_204

dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - '+.xboxlive.com'
    - 'msftconnecttest.com'
    - 'xbox.*.microsoft.com'
    - '*.battlenet.com.cn'
    - '*.battlenet.com'
    - '*.blzstatic.cn'
    - '*.battle.net'
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query

proxies:
            
proxy-groups:
  - {name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©, type: select, proxies: [ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹, ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹, ğŸ‘ é«˜çº§èŠ‚ç‚¹]}

  - {name: ğŸ“ˆ ç½‘ç»œæµ‹è¯•, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹, ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹]}

  - {name: ğŸŸ æ¼ç½‘ä¹‹é±¼, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©], disable-udp: true}

  - {name: âš¡ ç›´è¿åŸŸå, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}

  - {name: ğŸªœ ä»£ç†åŸŸå, type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©, ğŸ¯ å…¨çƒç›´è¿], disable-udp: true}

  - {name: ğŸ® å›½åŒºæ¸¸æˆ, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}

  - {name: â“‚ï¸ Microsoft ä¸­å›½, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}

  - {name: ğŸ—½ Google ä¸­å›½, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}

  - {name: ğŸ Apple ä¸­å›½, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}

  - {name: ğŸ‡¨ğŸ‡³ å›½å†… IP, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}

  - {name: âœˆï¸ Telegram, type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©]}

  - {name: ğŸ–¥ï¸ ç›´è¿è½¯ä»¶, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿]}

  - {name: ğŸ  ç§æœ‰ç½‘ç»œ, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿]}

  - {name: â›”ï¸ å¹¿å‘ŠåŸŸå, type: select, proxies: [ğŸ›‘ å…¨çƒæ‹¦æˆª]}

  - {name: ğŸ¯ å…¨çƒç›´è¿, type: select, proxies: [DIRECT]}

  - {name: ğŸ›‘ å…¨çƒæ‹¦æˆª, type: select, proxies: [REJECT]}

  # é‡‡ç”¨èŠ‚ç‚¹è´Ÿè½½å‡è¡¡ç­–ç•¥ï¼Œä¼˜ç‚¹æ˜¯æ›´ç¨³å®šï¼Œé€Ÿåº¦å¯èƒ½æœ‰æå‡ï¼›æ¨èåœ¨èŠ‚ç‚¹å¤ç”¨æ¯”è¾ƒå¤šçš„æƒ…å†µä¸‹ä½¿ç”¨
  - {name: ğŸ‘ é«˜çº§èŠ‚ç‚¹, type: load-balance, strategy: consistent-hashing, lazy: true, use: [ğŸ›« æˆ‘çš„æœºåœº], filter: "ä¸“çº¿"}
  
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, type: load-balance, strategy: consistent-hashing, lazy: true, use: [ğŸ›« æˆ‘çš„æœºåœº], filter: "(?=.*(é¦™æ¸¯).)^((?!(ä¸“çº¿)).)*$"}

  - {name: ğŸ‡¹ğŸ‡¼ å°æ¹¾èŠ‚ç‚¹, type: load-balance, strategy: consistent-hashing, lazy: true, use: [ğŸ›« æˆ‘çš„æœºåœº], filter: "(?=.*(å°æ¹¾).)^((?!(ä¸“çº¿)).)*$"} 

  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, type: load-balance, strategy: consistent-hashing, lazy: true, use: [ğŸ›« æˆ‘çš„æœºåœº], filter: "(?=.*(æ—¥æœ¬).)^((?!(ä¸“çº¿)).)*$"}

  - {name: ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹, type: load-balance, strategy: consistent-hashing, lazy: true, use: [ğŸ›« æˆ‘çš„æœºåœº], filter: "(?=.*(éŸ©å›½).)^((?!(ä¸“çº¿)).)*$"}

  - {name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡èŠ‚ç‚¹, type: load-balance, strategy: consistent-hashing, lazy: true, use: [ğŸ›« æˆ‘çš„æœºåœº], filter: "(?=.*(æ–°åŠ å¡).)^((?!(ä¸“çº¿)).)*$"}

  - {name: ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹, type: load-balance, strategy: consistent-hashing, lazy: true, use: [ğŸ›« æˆ‘çš„æœºåœº], filter: "(?=.*(ç¾å›½).)^((?!(ä¸“çº¿)).)*$"}

rule-providers:
  ads:
    type: http
    behavior: domain
    url: "https://fastly.jsdelivr.net/gh/DustinWin/clash-ruleset@release/ads.yaml"
    path: ./ruleset/ads.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://fastly.jsdelivr.net/gh/DustinWin/clash-ruleset@release/private.yaml"
    path: ./ruleset/private.yaml
    interval: 86400

  microsoft-cn:
    type: http
    behavior: domain
    url: "https://fastly.jsdelivr.net/gh/DustinWin/clash-ruleset@release/microsoft-cn.yaml"
    path: ./ruleset/microsoft-cn.yaml
    interval: 86400

  apple-cn:
    type: http
    behavior: domain
    url: "https://fastly.jsdelivr.net/gh/DustinWin/clash-ruleset@release/apple-cn.yaml"
    path: ./ruleset/apple-cn.yaml
    interval: 86400

  google-cn:
    type: http
    behavior: domain
    url: "https://fastly.jsdelivr.net/gh/DustinWin/clash-ruleset@release/google-cn.yaml"
    path: ./ruleset/google-cn.yaml
    interval: 86400

  games-cn:
    type: http
    behavior: domain
    url: "https://fastly.jsdelivr.net/gh/DustinWin/clash-ruleset@release/games-cn.yaml"
    path: ./ruleset/games-cn.yaml
    interval: 86400

  networktest:
    type: http
    behavior: classical
    url: "https://fastly.jsdelivr.net/gh/DustinWin/clash-ruleset@release/networktest.yaml"
    path: ./ruleset/networktest.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://fastly.jsdelivr.net/gh/DustinWin/clash-ruleset@release/applications.yaml"
    path: ./ruleset/applications.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://fastly.jsdelivr.net/gh/DustinWin/clash-ruleset@release/proxy.yaml"
    path: ./ruleset/proxy.yaml
    interval: 86400

  cn:
    type: http
    behavior: domain
    url: "https://fastly.jsdelivr.net/gh/DustinWin/clash-ruleset@release/cn.yaml"
    path: ./ruleset/cn.yaml
    interval: 86400

  telegramip:
    type: http
    behavior: ipcidr
    url: "https://fastly.jsdelivr.net/gh/DustinWin/clash-ruleset@release/telegramip.yaml"
    path: ./ruleset/telegramip.yaml
    interval: 86400

  privateip:
    type: http
    behavior: ipcidr
    url: "https://fastly.jsdelivr.net/gh/DustinWin/clash-ruleset@release/privateip.yaml"
    path: ./ruleset/privateip.yaml
    interval: 86400

  cnip:
    type: http
    behavior: ipcidr
    url: "https://fastly.jsdelivr.net/gh/DustinWin/clash-ruleset@release/cnip.yaml"
    path: ./ruleset/cnip.yaml
    interval: 86400

rules:
  - RULE-SET,ads,â›”ï¸ å¹¿å‘ŠåŸŸå
  - RULE-SET,private,ğŸ  ç§æœ‰ç½‘ç»œ
  - RULE-SET,microsoft-cn,â“‚ï¸ Microsoft ä¸­å›½
  - RULE-SET,apple-cn,ğŸ Apple ä¸­å›½
  - RULE-SET,google-cn,ğŸ—½ Google ä¸­å›½
  - RULE-SET,games-cn,ğŸ® å›½åŒºæ¸¸æˆ
  - RULE-SET,networktest,ğŸ“ˆ ç½‘ç»œæµ‹è¯•
  - RULE-SET,applications,ğŸ–¥ï¸ ç›´è¿è½¯ä»¶
  - RULE-SET,proxy,ğŸªœ ä»£ç†åŸŸå
  - RULE-SET,cn,âš¡ ç›´è¿åŸŸå
  - RULE-SET,telegramip,âœˆï¸ Telegram
  - RULE-SET,privateip,ğŸ  ç§æœ‰ç½‘ç»œ,no-resolve
  - RULE-SET,cnip,ğŸ‡¨ğŸ‡³ å›½å†… IP
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼